version: '2'

services:
  database:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - /var/tmp/fiap-restaurant-app/pagamento:/home/dynamodblocal/data

  database-gui:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "sa-east-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - database

  app:
    container_name: fiap-restaurant-app-pagamento
    depends_on:
      - database
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - /var/tmp/fiap-restaurant-app/pagamento/app:/var/html/fiap-restaurant-app/pagamento
